### ISSUE TITLE
Setup paths in liveness/readiness probes

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#543]
Flere av applikasjonene mangler path i probespec.
Dette skaper problemer hvis f.eks. ingressen slettes og opprettes på nytt, da healthchecks blir opprettet basert på denne specen. Hvis path ikke finnes, defaulter den til / , men vi har flere applikasjoner som er satt opp slik at healthcheck skal gå mot /ready, og / ikke gir et forventet svar.
GCP vil da bli kranglete og svare 502 for aktuell path, selv om applikasjonen egentlig virker.

Har stort sett løst dette ved å oppdatere healthchecken manuelt hvis nødvendig, da den er mer eller mindre statisk.
Ser nå at dette burde være definert i spec, slik at vi eliminerer behov for manuelt arbeid.

- [ ] Identifiser applikasjoner med manglende spec
- [ ] Legg inn aktuell ping/ready path i samtlige

Eksempel (fdk-harvest-admin):
```
      livenessProbe:
            httpGet:
              path: /api/datasources
              port: 8080
          (...)
       readinessProbe:
            httpGet:
              path: /api/datasources
              port: 8080
```
