### ISSUE TITLE
Resources requests på alle applikasjoner

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#730]
De fleste applikasjonene har idag resource requests mht containeren, men limits har vi bare satt for en håndfull.
Dette gjør at tjenester kan trekke alle ressursene tilgjengelig i en node, før de omsider blir stoppet.
Alle applikasjoner burde settes opp med både request og limit, satt til en passende mengde.

```
spec:
  containers:
     resources:
        requests:
           memory: "1000Mi"
           cpu: "100m"
        limits:
           memory: "2000Mi"
           cpu: "200m"
```
